version: "3"
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    # volumes:
    #   - ./frontend/build:/app/frontend/build
    networks:
      - my_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - my_network

networks:
  my_network:
