version: "3"

services:
  nextjs:
    build:
      context: . # Path to your Next.js app directory
      dockerfile: Dockerfile # Path to the Dockerfile for Next.js
    ports:
      - "3000:3000" # Map the Next.js app port
    networks:
      - mynetwork

  nginx:
    build:
      context: ./nginx-conf # Path to the directory containing Nginx configuration
      dockerfile: Dockerfile # Path to the Dockerfile for Nginx
    ports:
      - "80:80" # Map the Nginx server port
    networks:
      - mynetwork
    depends_on:
      - nextjs

networks:
  mynetwork:
